// src/routes/ghost-system/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fetchGhostPostWindows, fetchGhostNames } from '$lib/api';
  import { toast } from '$lib/toast-store';
  import Header from '$lib/components/header.svelte';
  import Skeleton from '$lib/components/skeleton.svelte';
  import type { GhostPostWindow, GhostName } from '$lib/api';

  let ghostWindows = $state([]);
  let ghostNames = $state([]);
  let loading = $state(false);
  let ghostPostsEnabled = $state(true);
  let defaultDuration = $state('24');

  onMount(async () => {
    loading = true;
    ghostWindows = await fetchGhostPostWindows();
    ghostNames = await fetchGhostNames();
    loading = false;
  });

  function handleToggleGhostPosts() {
    ghostPostsEnabled = !ghostPostsEnabled;
    toast.success(`Ghost Posts ${ghostPostsEnabled ? 'enabled' : 'disabled'}`);
  }
</script>

<div class="flex-1">
  <Header title="Ghost System Management" description="Manage ghost posts, windows, and names" />

  <div class="p-8 space-y-8">
    <!-- Ghost Post Settings -->
    <div class="bg-white rounded-lg border border-border p-6">
      <h2 class="text-lg font-bold text-foreground mb-4">Ghost Post Settings</h2>
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="font-medium text-foreground">Enable Ghost Posts for Entire App</p>
            <p class="text-xs text-muted-foreground">Allow users to post anonymously</p>
          </div>
          <button
            onclick={handleToggleGhostPosts}
            class={`px-4 py-2 rounded-md text-sm font-medium ${
              ghostPostsEnabled ? 'bg-primary text-primary-foreground' : 'bg-secondary text-foreground'
            }`}
          >
            {ghostPostsEnabled ? 'Enabled' : 'Disabled'}
          </button>
        </div>

        <!-- Removed label and fixed form control association -->
        <div class="border-t border-border pt-4">
          <p class="block text-sm font-medium text-foreground mb-2">Default Ghost Post Duration</p>
          <select bind:value={defaultDuration} class="px-4 py-2 border border-border rounded-md text-sm">
            <option value="30">30 minutes</option>
            <option value="60">1 hour</option>
            <option value="360">6 hours</option>
            <option value="1440">24 hours</option>
            <option value="2880">48 hours</option>
          </select>
        </div>
      </div>
    </div>

    <!-- Ghost Post Windows -->
    <div>
      <h2 class="text-lg font-bold text-foreground mb-4">Ghost Post Windows</h2>
      <div class="rounded-lg border border-border overflow-hidden">
        <table class="w-full text-sm">
          <thead class="bg-secondary">
            <tr>
              <th class="px-6 py-3 text-left font-semibold">Start Time</th>
              <th class="px-6 py-3 text-left font-semibold">End Time</th>
              <th class="px-6 py-3 text-left font-semibold">Status</th>
              <th class="px-6 py-3 text-left font-semibold">Notification Sent</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-border">
            {#if loading}
              {#each Array(3) as _}
                <tr class="bg-white">
                  <td class="px-6 py-4"><Skeleton className="h-4 w-32" /></td>
                  <td class="px-6 py-4"><Skeleton className="h-4 w-32" /></td>
                  <td class="px-6 py-4"><Skeleton className="h-4 w-16" /></td>
                  <td class="px-6 py-4"><Skeleton className="h-4 w-12" /></td>
                </tr>
              {/each}
            {:else if ghostWindows.length > 0}
              {#each ghostWindows as window (window.id)}
                <tr class="bg-white hover:bg-gray-50">
                  <td class="px-6 py-4 text-muted-foreground">{window.startTime}</td>
                  <td class="px-6 py-4 text-muted-foreground">{window.endTime}</td>
                  <td class="px-6 py-4">
                    <span class={`px-2 py-1 rounded-full text-xs font-medium ${
                      window.status === 'active' ? 'bg-green-100 text-green-700' : 
                      window.status === 'upcoming' ? 'bg-blue-100 text-blue-700' : 
                      'bg-gray-100 text-gray-700'
                    }`}>
                      {window.status}
                    </span>
                  </td>
                  <td class="px-6 py-4">
                    {#if window.notificationSent}
                      <span class="text-green-600">✓</span>
                    {:else}
                      <span class="text-gray-400">✗</span>
                    {/if}
                  </td>
                </tr>
              {/each}
            {/if}
          </tbody>
        </table>
      </div>
    </div>

    <!-- Ghost Names -->
    <div>
      <h2 class="text-lg font-bold text-foreground mb-4">Ghost Names Management</h2>
      <div class="rounded-lg border border-border overflow-hidden">
        <table class="w-full text-sm">
          <thead class="bg-secondary">
            <tr>
              <th class="px-6 py-3 text-left font-semibold">Ghost Name</th>
              <th class="px-6 py-3 text-left font-semibold">Status</th>
              <th class="px-6 py-3 text-left font-semibold">Usage Count</th>
              <th class="px-6 py-3 text-left font-semibold">Last Used</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-border">
            {#if loading}
              {#each Array(3) as _}
                <tr class="bg-white">
                  <td class="px-6 py-4"><Skeleton className="h-4 w-24" /></td>
                  <td class="px-6 py-4"><Skeleton className="h-4 w-16" /></td>
                  <td class="px-6 py-4"><Skeleton className="h-4 w-12" /></td>
                  <td class="px-6 py-4"><Skeleton className="h-4 w-20" /></td>
                </tr>
              {/each}
            {:else if ghostNames.length > 0}
              {#each ghostNames as ghostName (ghostName.id)}
                <tr class="bg-white hover:bg-gray-50">
                  <td class="px-6 py-4 font-medium text-foreground">{ghostName.name}</td>
                  <td class="px-6 py-4">
                    <span class={`px-2 py-1 rounded-full text-xs font-medium ${
                      ghostName.status === 'allowed' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                    }`}>
                      {ghostName.status}
                    </span>
                  </td>
                  <td class="px-6 py-4 text-muted-foreground">{ghostName.usageCount}</td>
                  <td class="px-6 py-4 text-muted-foreground">{ghostName.lastUsed}</td>
                </tr>
              {/each}
            {/if}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

// app/ghost-system/page.tsx
"use client"

import { useState, useEffect } from "react"
import Header from "@/components/header"
import { Button } from "@/components/ui/button"
import { TableSkeleton } from "@/components/skeleton"
import { getGhostPosts } from "@/lib/api"
import { ChevronLeft, ChevronRight } from "lucide-react"

export default function GhostSystemPage() {
  const [posts, setPosts] = useState([])
  const [loading, setLoading] = useState(true)
  const [page, setPage] = useState(1)
  const [total, setTotal] = useState(0)

  const pageSize = 10

  useEffect(() => {
    setLoading(true)
    getGhostPosts(page, pageSize).then((data) => {
      setPosts(data.posts)
      setTotal(data.total)
      setLoading(false)
    })
  }, [page])

  const totalPages = Math.ceil(total / pageSize)

  return (
    <div>
      <Header title="Ghost System" description="Anonymous posts and ghost interactions" />

      <div className="p-8 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-white rounded-lg border border-border p-6">
            <p className="text-sm text-muted-foreground">Total Ghost Posts</p>
            <p className="text-3xl font-bold text-primary mt-2">1,847</p>
          </div>
          <div className="bg-white rounded-lg border border-border p-6">
            <p className="text-sm text-muted-foreground">Active This Hour</p>
            <p className="text-3xl font-bold text-primary mt-2">342</p>
          </div>
          <div className="bg-white rounded-lg border border-border p-6">
            <p className="text-sm text-muted-foreground">Avg Engagement</p>
            <p className="text-3xl font-bold text-primary mt-2">847</p>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-border overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-secondary/50 border-b border-border">
                <tr>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Content</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Author</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Likes</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Comments</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Created</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {loading ? (
                  <tr>
                    <td colSpan={6} className="px-6 py-6">
                      <TableSkeleton />
                    </td>
                  </tr>
                ) : (
                  posts.map((post: any) => (
                    <tr key={post.id} className="hover:bg-secondary/30 transition-colors">
                      <td className="px-6 py-4 text-sm text-foreground max-w-xs truncate">{post.content}</td>
                      <td className="px-6 py-4 text-sm font-medium text-primary">{post.author}</td>
                      <td className="px-6 py-4 text-sm text-foreground">{post.likes}</td>
                      <td className="px-6 py-4 text-sm text-foreground">{post.comments}</td>
                      <td className="px-6 py-4 text-sm text-muted-foreground">{post.createdAt}</td>
                      <td className="px-6 py-4 text-sm">
                        <Button size="sm" variant="ghost">
                          View
                        </Button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        <div className="flex items-center justify-between">
          <p className="text-sm text-muted-foreground">
            Showing {Math.min((page - 1) * pageSize + 1, total)} to {Math.min(page * pageSize, total)} of {total} posts
          </p>
          <div className="flex gap-2">
            <Button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page === 1}
              variant="outline"
              size="sm"
            >
              <ChevronLeft className="w-4 h-4" />
            </Button>
            {Array.from({ length: Math.min(5, totalPages) }).map((_, i) => {
              const pageNum = page > 3 ? page + i - 2 : i + 1
              return pageNum <= totalPages ? (
                <Button
                  key={pageNum}
                  onClick={() => setPage(pageNum)}
                  variant={pageNum === page ? "default" : "outline"}
                  size="sm"
                >
                  {pageNum}
                </Button>
              ) : null
            })}
            <Button
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page === totalPages}
              variant="outline"
              size="sm"
            >
              <ChevronRight className="w-4 h-4" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
