// app/content/page.tsx
"use client"

import { useState, useEffect } from "react"
import Header from "@/components/header"
import { Button } from "@/components/ui/button"
import { TableSkeleton } from "@/components/skeleton"
import { getContentFlags, reviewContent } from "@/lib/api"
import { toast } from "sonner"
import { ChevronLeft, ChevronRight, CheckCircle, Eye } from "lucide-react"

export default function ContentPage() {
  const [flags, setFlags] = useState([])
  const [loading, setLoading] = useState(true)
  const [page, setPage] = useState(1)
  const [total, setTotal] = useState(0)
  const [statusFilter, setStatusFilter] = useState("all")

  const pageSize = 10

  useEffect(() => {
    setLoading(true)
    getContentFlags(page, pageSize).then((data) => {
      setFlags(data.flags)
      setTotal(data.total)
      setLoading(false)
    })
  }, [page])

  const filteredFlags = flags.filter((flag: any) => statusFilter === "all" || flag.status === statusFilter)

  const totalPages = Math.ceil(total / pageSize)

  const handleReview = async (flagId: string, action: "approve" | "hide") => {
    try {
      await reviewContent(flagId, action)
      toast.success(`Content ${action === "approve" ? "approved" : "hidden"} successfully`)
      setFlags(flags.filter((f: any) => f.id !== flagId))
    } catch (error) {
      toast.error("Failed to review content")
    }
  }

  return (
    <div>
      <Header title="Content Moderation" description="Review and manage flagged content" />

      <div className="p-8 space-y-6">
        <div>
          <label className="text-sm font-medium text-foreground mb-2 block">Filter by Status</label>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-4 py-2 border border-border rounded-lg text-sm"
          >
            <option value="all">All Status</option>
            <option value="pending">Pending</option>
            <option value="reviewed">Reviewed</option>
            <option value="hidden">Hidden</option>
          </select>
        </div>

        <div className="bg-white rounded-lg border border-border overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-secondary/50 border-b border-border">
                <tr>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Post ID</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Content Preview</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Reason</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Author</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Status</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-foreground">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {loading ? (
                  <tr>
                    <td colSpan={6} className="px-6 py-6">
                      <TableSkeleton />
                    </td>
                  </tr>
                ) : (
                  filteredFlags.map((flag: any) => (
                    <tr key={flag.id} className="hover:bg-secondary/30 transition-colors">
                      <td className="px-6 py-4 text-sm font-mono text-muted-foreground">{flag.postId}</td>
                      <td className="px-6 py-4 text-sm text-foreground max-w-xs truncate">{flag.content}</td>
                      <td className="px-6 py-4 text-sm text-foreground">{flag.reason}</td>
                      <td className="px-6 py-4 text-sm text-primary">{flag.author}</td>
                      <td className="px-6 py-4 text-sm">
                        <span
                          className={`px-3 py-1 rounded-full text-xs font-medium ${
                            flag.status === "pending"
                              ? "bg-yellow-100 text-yellow-700"
                              : flag.status === "reviewed"
                                ? "bg-blue-100 text-blue-700"
                                : "bg-primary/10 text-primary"
                          }`}
                        >
                          {flag.status.charAt(0).toUpperCase() + flag.status.slice(1)}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-sm flex gap-2">
                        {flag.status === "pending" && (
                          <>
                            <Button size="sm" variant="ghost" onClick={() => handleReview(flag.id, "approve")}>
                              <CheckCircle className="w-4 h-4 mr-1" />
                              Approve
                            </Button>
                            <Button size="sm" variant="ghost" onClick={() => handleReview(flag.id, "hide")}>
                              <Eye className="w-4 h-4 mr-1" />
                              Hide
                            </Button>
                          </>
                        )}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        <div className="flex items-center justify-between">
          <p className="text-sm text-muted-foreground">
            Showing {Math.min((page - 1) * pageSize + 1, total)} to {Math.min(page * pageSize, total)} of {total} flags
          </p>
          <div className="flex gap-2">
            <Button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page === 1}
              variant="outline"
              size="sm"
            >
              <ChevronLeft className="w-4 h-4" />
            </Button>
            {Array.from({ length: Math.min(5, totalPages) }).map((_, i) => {
              const pageNum = page > 3 ? page + i - 2 : i + 1
              return pageNum <= totalPages ? (
                <Button
                  key={pageNum}
                  onClick={() => setPage(pageNum)}
                  variant={pageNum === page ? "default" : "outline"}
                  size="sm"
                >
                  {pageNum}
                </Button>
              ) : null
            })}
            <Button
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page === totalPages}
              variant="outline"
              size="sm"
            >
              <ChevronRight className="w-4 h-4" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/routes/content/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fetchContent } from '$lib/api';
  import { toast } from '$lib/toast-store';
  import Header from '$lib/components/header.svelte';
  import Skeleton from '$lib/components/skeleton.svelte';
  import type { ContentItem } from '$lib/api';

  let content = $state<ContentItem[]>([]);
  let loading = $state(false);
  let filterTab = $state('all');

  onMount(async () => {
    loading = true;
    content = await fetchContent();
    loading = false;
  });

  function handleDelete(id: string) {
    toast.success('Content deleted');
  }

  function handleBanUser(author: string) {
    toast.success(`User ${author} has been banned`);
  }
</script>

<div class="flex-1">
  <Header title="Content Moderation" description="Review and manage reported content" />

  <div class="p-8 space-y-6">
    <!-- Filter Tabs -->
    <div class="flex gap-2 border-b border-border">
      {#each ['all', 'reported', 'explicit', 'under-18'] as tab}
        <button
          onclick={() => filterTab = tab}
          class={`px-4 py-2 font-medium text-sm border-b-2 transition-colors ${
            filterTab === tab
              ? 'border-primary text-primary'
              : 'border-transparent text-muted-foreground hover:text-foreground'
          }`}
        >
          {tab === 'all' ? 'All Content' : tab === 'reported' ? 'Reported' : tab === 'explicit' ? 'Explicit' : 'Under-18'}
        </button>
      {/each}
    </div>

    <!-- Content Table -->
    <div class="rounded-lg border border-border overflow-hidden">
      <table class="w-full text-sm">
        <thead class="bg-secondary">
          <tr>
            <th class="px-6 py-3 text-left font-semibold">Content</th>
            <th class="px-6 py-3 text-left font-semibold">Author</th>
            <th class="px-6 py-3 text-left font-semibold">Type</th>
            <th class="px-6 py-3 text-left font-semibold">Flags</th>
            <th class="px-6 py-3 text-left font-semibold">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-border">
          {#if loading}
            {#each Array(5) as _}
              <tr class="bg-white">
                <td class="px-6 py-4"><Skeleton className="h-4 w-32" /></td>
                <td class="px-6 py-4"><Skeleton className="h-4 w-24" /></td>
                <td class="px-6 py-4"><Skeleton className="h-4 w-16" /></td>
                <td class="px-6 py-4"><Skeleton className="h-4 w-20" /></td>
                <td class="px-6 py-4"><Skeleton className="h-4 w-24" /></td>
              </tr>
            {/each}
          {:else if content.length > 0}
            {#each content as item (item.id)}
              <tr class="bg-white hover:bg-gray-50">
                <td class="px-6 py-4">
                  <div class="flex items-center gap-3">
                    <span class="text-2xl">{item.thumbnail}</span>
                    <p class="text-muted-foreground text-xs max-w-xs truncate">{item.text}</p>
                  </div>
                </td>
                <td class="px-6 py-4">
                  <div>
                    <p class="font-medium text-foreground">@{item.author}</p>
                    <p class="text-xs text-muted-foreground">{item.authorAge} years old</p>
                  </div>
                </td>
                <td class="px-6 py-4 text-muted-foreground">{item.type}</td>
                <td class="px-6 py-4">
                  {#if item.flags.length > 0}
                    <span class="px-2 py-1 rounded-full text-xs bg-red-100 text-red-700">{item.flags[0]}</span>
                  {/if}
                </td>
                <td class="px-6 py-4">
                  <div class="flex gap-2">
                    <button
                      onclick={() => handleDelete(item.id)}
                      class="text-red-600 hover:underline text-xs font-medium"
                    >
                      Delete
                    </button>
                    <button
                      onclick={() => handleBanUser(item.author)}
                      class="text-orange-600 hover:underline text-xs font-medium"
                    >
                      Ban
                    </button>
                  </div>
                </td>
              </tr>
            {/each}
          {/if}
        </tbody>
      </table>
    </div>
  </div>
</div>
