// src/lib/components/metric-card.svelte
<script lang="ts">
  interface Props {
    label?: string;
    value?: string;
    icon?: string;
    trend?: string;
    trendUp?: boolean;
  }

  let {
    label = '',
    value = '0',
    icon = '📊',
    trend = '',
    trendUp = true
  }: Props = $props();
</script>

<div class="bg-white border border-border rounded-lg p-6 hover:shadow-md transition-shadow">
  <div class="flex items-start justify-between">
    <div>
      <p class="text-muted-foreground text-sm font-medium">{label}</p>
      <p class="text-3xl font-bold text-foreground mt-2">{value}</p>
      {#if trend}
        <p class={`text-xs mt-2 ${trendUp ? 'text-green-600' : 'text-red-600'}`}>
          {trendUp ? '↑' : '↓'} {trend}
        </p>
      {/if}
    </div>
    <div class="text-3xl">{icon}</div>
  </div>
</div>

// components/metric-card.tsx
import { TrendingUp, TrendingDown } from "lucide-react"

interface MetricCardProps {
  label: string
  value: string
  icon: string
  trend: string
  trendUp: boolean
}

export default function MetricCard({ label, value, icon, trend, trendUp }: MetricCardProps) {
  return (
    <div className="bg-white rounded-lg border border-border p-6 hover:shadow-md transition-shadow">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <p className="text-sm text-muted-foreground mb-2">{label}</p>
          <p className="text-3xl font-bold text-foreground">{value}</p>
          <div className={`flex items-center gap-1 mt-2 text-xs ${trendUp ? "text-green-600" : "text-red-600"}`}>
            {trendUp ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}
            <span>{trend}</span>
          </div>
        </div>
        <div className="text-3xl">{icon}</div>
      </div>
    </div>
  )
}
