// components/sidebar.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import {
  LayoutDashboard,
  Users,
  Users2,
  Bell,
  Zap,
  Wind,
  Eye,
  Settings,
  Ticket,
  BarChart3,
  Shield,
  CheckCircle,
} from "lucide-react"
import { cn } from "@/lib/utils"

const navigation = [
  { href: "/", label: "Dashboard", icon: LayoutDashboard },
  { href: "/users", label: "User Management", icon: Users },
  { href: "/groups", label: "Groups", icon: Users2 },
  { href: "/notifications", label: "Push Notifications", icon: Bell },
  { href: "/ghost-system", label: "Ghost System", icon: Zap },
  { href: "/fomo-windows", label: "FOMO Windows", icon: Wind },
  { href: "/content", label: "Content Moderation", icon: Eye },
  { href: "/ai-settings", label: "AI & Automation", icon: Settings },
  { href: "/verification", label: "Verification", icon: CheckCircle },
  { href: "/support", label: "Support Tickets", icon: Ticket },
  { href: "/ads", label: "Ad Campaigns", icon: BarChart3 },
  { href: "/security", label: "Security", icon: Shield },
]

export default function Sidebar() {
  const pathname = usePathname()

  return (
    <aside className="fixed left-0 top-0 h-screen w-64 bg-white border-r border-border overflow-y-auto shadow-md">
      <div className="p-6 border-b border-border">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center text-white font-bold text-base shadow-lg">
            CR
          </div>
          <div>
            <h1 className="font-bold text-lg text-foreground">Casa Rancha</h1>
            <p className="text-xs text-muted-foreground">Admin Panel</p>
          </div>
        </div>
      </div>

      <nav className="px-3 py-6 space-y-2">
        {navigation.map((item) => {
          const Icon = item.icon
          const isActive = pathname === item.href
          return (
            <Link
              key={item.href}
              href={item.href}
              className={cn(
                "flex items-center gap-3 px-4 py-2.5 rounded-lg transition-all duration-200 font-medium text-sm",
                isActive
                  ? "bg-primary text-primary-foreground shadow-md scale-[1.02]"
                  : "text-foreground hover:bg-secondary/80 hover:text-primary",
              )}
            >
              <Icon className="w-5 h-5" />
              <span>{item.label}</span>
            </Link>
          )
        })}
      </nav>
    </aside>
  )
}

// src/lib/components/sidebar.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';

  const menuItems = [
    { label: 'Dashboard', icon: '📊', href: '/' },
    { label: 'Users', icon: '👥', href: '/users' },
    { label: 'Groups', icon: '👫', href: '/groups' },
    { label: 'Push Notifications', icon: '🔔', href: '/notifications' },
    { label: 'Ghost System', icon: '👻', href: '/ghost-system' },
    { label: 'FOMO Windows', icon: '⏰', href: '/fomo' },
    { label: 'Content Moderation', icon: '🚫', href: '/content' },
    { label: 'AI Settings', icon: '🤖', href: '/ai-settings' },
    { label: 'Verification', icon: '✓', href: '/verification' },
    { label: 'Support Tickets', icon: '🎫', href: '/tickets' },
    { label: 'Ad Campaigns', icon: '📢', href: '/ads' },
  ];

  function isActive(href: string) {
    return $page.url.pathname === href;
  }
</script>

<div class="h-screen bg-sidebar-background border-r border-sidebar-border overflow-y-auto fixed w-64 p-6">
  <div class="mb-8">
    <div class="flex items-center gap-2 mb-2">
      <span class="text-2xl">🏘️</span>
      <h1 class="text-xl font-bold text-sidebar-primary">Casa Rancha</h1>
    </div>
    <p class="text-xs text-sidebar-foreground/60">Admin Dashboard</p>
  </div>

  <nav class="space-y-2">
    {#each menuItems as item}
      <button
        onclick={() => goto(item.href)}
        class={`w-full text-left px-4 py-2 rounded-md flex items-center gap-3 text-sm font-medium transition-colors ${
          isActive(item.href)
            ? 'bg-sidebar-primary text-sidebar-primary-foreground'
            : 'text-sidebar-foreground hover:bg-sidebar-accent'
        }`}
      >
        <span class="text-lg">{item.icon}</span>
        {item.label}
      </button>
    {/each}
  </nav>
</div>
